apiVersion: apps/v1
kind: Deployment
metadata:
  name: hshar-deployment
  labels:
    web: hshar
spec:
  replicas: 1
  selector:
    matchLabels:
      web: hshar
  template:
    metadata:
      labels:
        web: hshar
    spec:
      containers:
      - name: hshar
        image: venkatnarayan16/hshar
        ports:
          - containerPort: 80
