apiVersion: apps/v1
kind: Deployment
metadata:
  name: hshar-deployment
  labels:
    web: hshar
spec:
  replicas: 1
  selector:
    matchLabels:
      web: hshar
  template:
    metadata:
      labels:
        web: hshar
    spec:
      containers:
      - name: hshar
        image: venkatnarayan16/website
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hshar-service
spec:
  type: NodePort
  selector:
    web: hshar
  ports:
    - port: 80
      nodePort: 30008  
